/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ndk_lingxiao_ndkproject_Hello */

#ifndef _Included_com_ndk_lingxiao_ndkproject_Hello
#define _Included_com_ndk_lingxiao_ndkproject_Hello
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_ndk_lingxiao_ndkproject_Hello
 * Method:    callStaticMethod
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_ndk_lingxiao_ndkproject_Hello_callStaticMethod__I
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_ndk_lingxiao_ndkproject_Hello
 * Method:    callStaticMethod
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ndk_lingxiao_ndkproject_Hello_callStaticMethod__JLjava_lang_String_2
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_ndk_lingxiao_ndkproject_Hello
 * Method:    callInstanceMethod
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_ndk_lingxiao_ndkproject_Hello_callInstanceMethod__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_ndk_lingxiao_ndkproject_Hello
 * Method:    callInstanceMethod
 * Signature: (Ljava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_com_ndk_lingxiao_ndkproject_Hello_callInstanceMethod__Ljava_lang_String_2J
  (JNIEnv *, jobject, jstring, jlong);

#ifdef __cplusplus
}
#endif
#endif
extern "C"
JNIEXPORT void JNICALL
Java_com_ndk_lingxiao_ndkproject_Hello_callStaticMethod__I(JNIEnv *env, jclass type, jint i) {

    // TODO

}